apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: accesshive-ingress
  namespace: {{ .Values.environment.name | lower }}
spec:
  ingressClassName: nginx
  {{- if eq .Values.environment.name "Development" }}
  tls:
    - hosts:
        - accesshiveapi.dev.com
      secretName: accesshiveapidev-tls
  {{- end }}
  rules:
    # - host: rabbitmq.{{ .Values.environment.shortName }}.com
    -  http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: rabbitmsg-service
                port:
                  number: 80
    # - host: accesshiveapi.{{ .Values.environment.shortName }}.com
    -  http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: accesshive-api-service
                port:
                  number: 80
