apiVersion: v1
kind: ConfigMap
metadata:
  name: accesshive-api-config
  namespace: {{ .Values.environment.name | lower }}
data:
  ConnectionStrings__DBConnectionString: Server=sqlserver-service;Database=AccessHiveDB;User Id=sa;Password=Admin1234;TrustServerCertificate=True
  ConnectionStrings__RMQConnectionString: rabbitmq-service
  ASPNETCORE_ENVIRONMENT: {{ .Values.environment.name }}
  ASPNETCORE_ENV_VERSION: v2
