apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: accesshive-ingress
  namespace: development
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - accesshiveapi.dev.com
      secretName: accesshiveapidev-tls
  rules:
    - host: rabbitmq.dev.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: rabbitmsg-service
                port:
                  number: 80
    - host: accesshiveapi.dev.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: accesshive-api-service
                port:
                  number: 80
