apiVersion: v1
kind: ConfigMap
metadata:
  name: accesshive-api-config
data:
  ConnectionStrings__DBConnectionString: Server=sqlserver-service;Database=AccessHiveDB;User Id=sa;Password=Admin1234;TrustServerCertificate=True
  ConnectionStrings__RMQConnectionString: rabbitmq-service
