# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

variables:
  tag: "$(Build.BuildId)"

stages:
  - stage: build
    displayName: build image
    jobs:
      - job: build
        displayName: build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Build and push an image
            inputs:
              containerRegistry: "Docker Hub"
              repository: "joeipe/accesshiveapi"
              command: "buildAndPush"
              dockerfile: "$(Build.SourcesDirectory)/AccessHive.API/Dockerfile"
              buildContext: "$(Build.SourcesDirectory)"
              tags: |
                $(tag)

          - task: Docker@2
            displayName: Build and push an image az
            inputs:
              containerRegistry: 'accesshiveregistry'
              repository: 'accesshiveapi'
              command: 'buildAndPush'
              Dockerfile: '$(Build.SourcesDirectory)/AccessHive.API/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)'
              tags: '$(tag)'

  - stage: deploy_to_prod
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: deployToKubernetes
        displayName: "DeployToKubernetes - Prod"
        steps:
          - task: HelmDeploy@0
            displayName: Helm upgrade
            inputs:
              connectionType: "Azure Resource Manager"
              azureSubscription: "Personal-Sub(57f4859b-8037-4106-ac17-61520b9de19b)"
              azureResourceGroup: "k8sLearning-rg"
              kubernetesCluster: "accesshiveaks"
              command: "upgrade"
              chartType: "FilePath"
              chartPath: "$(Build.SourcesDirectory)/chart/accesshive"
              releaseName: "prod-accesshive"
              overrideValues: 'environment.name=Production,service.type=LoadBalancer,image.repository=accesshiveregistry.azurecr.io,image.tag="$(tag)"'
