# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

variables:
  tag: "$(Build.BuildId)"

stages:
  - stage: build
    displayName: build image
    jobs:
      - job: build
        displayName: build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Build and push an image
            inputs:
              containerRegistry: "Docker Hub"
              repository: "joeipe/accesshiveapi"
              command: "buildAndPush"
              dockerfile: "$(Build.SourcesDirectory)/AccessHive.API/Dockerfile"
              buildContext: "$(Build.SourcesDirectory)"
              tags: |
                latest

  - stage: deploy_to_prod
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: deployToKubernetes
        displayName: "DeployToKubernetes - Prod"
        steps:
          - script: echo todo
            displayName: todo

          - task: Kubernetes@1
            displayName: kubectl apply -f .\k8s\sqlserver.yml
            inputs:
              connectionType: "Azure Resource Manager"
              azureSubscriptionEndpoint: "Personal-Sub(57f4859b-8037-4106-ac17-61520b9de19b)"
              azureResourceGroup: "k8sLearning-rg"
              kubernetesCluster: "accesshiveaks"
              command: "apply"
              arguments: "-f $(Build.SourcesDirectory)/k8s/sqlserver.yml"

          - task: Kubernetes@1
            displayName: kubectl apply -f .\k8s\rabbitmq.yml
            inputs:
              connectionType: "Azure Resource Manager"
              azureSubscriptionEndpoint: "Personal-Sub(57f4859b-8037-4106-ac17-61520b9de19b)"
              azureResourceGroup: "k8sLearning-rg"
              kubernetesCluster: "accesshiveaks"
              command: "apply"
              arguments: "-f $(Build.SourcesDirectory)/k8s/rabbitmq.yml"

          - task: Kubernetes@1
            displayName: kubectl apply -f .\k8s\accesshiveapi.configmap.yml
            inputs:
              connectionType: "Azure Resource Manager"
              azureSubscriptionEndpoint: "Personal-Sub(57f4859b-8037-4106-ac17-61520b9de19b)"
              azureResourceGroup: "k8sLearning-rg"
              kubernetesCluster: "accesshiveaks"
              command: "apply"
              arguments: "-f $(Build.SourcesDirectory)/k8s/accesshiveapi.configmap.yml"

          - task: Kubernetes@1
            displayName: kubectl apply -f .\k8s\accesshiveapi.yml
            inputs:
              connectionType: "Azure Resource Manager"
              azureSubscriptionEndpoint: "Personal-Sub(57f4859b-8037-4106-ac17-61520b9de19b)"
              azureResourceGroup: "k8sLearning-rg"
              kubernetesCluster: "accesshiveaks"
              command: "apply"
              arguments: "-f $(Build.SourcesDirectory)/k8s/accesshiveapi.yml"
