# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

variables:
  tag: "$(Build.BuildId)"

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Build and push an image
            inputs:
              containerRegistry: "Docker Hub"
              repository: "joeipe/accesshiveapi"
              command: "buildAndPush"
              dockerfile: "$(Build.SourcesDirectory)/AccessHive.API/Dockerfile"
              buildContext: "$(Build.SourcesDirectory)"
              tags: |
                latest

  - stage: deploy_to_test
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
    jobs:
      - job: deployToAppService
        displayName: "DeployToAppService - Test"
        steps:
          - script: echo todo
            displayName: todo
